services:
  - type: web
    name: study-room-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
  - type: web
    name: study-room-realtime
    runtime: node
    rootDir: server-realtime
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
